# Sniperkit-Bot
# - Status: analyzed

language: go

go:
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - DBUSER=postgres DBPASS=

services:
  - docker
  - postgresql
  - rabbitmq

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database testing;' -U postgres

script:
  - make test-coverage
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
  - make no-changes-in-commit

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - DOCKER_PUSH_LATEST=1 make docker-push
